export const COUNTRIES = [
    { code: 'SA', name: 'المملكة العربية السعودية' },
    { code: 'AE', name: 'الإمارات العربية المتحدة' },
    { code: 'KW', name: 'الكويت' },
    { code: 'QA', name: 'قطر' },
    { code: 'BH', name: 'البحرين' },
    { code: 'OM', name: 'سلطنة عمان' },
    { code: 'YE', name: 'اليمن' },
    { code: 'EG', name: 'مصر' },
    { code: 'SD', name: 'السودان' },
    { code: 'JO', name: 'الأردن' },
    { code: 'LB', name: 'لبنان' },
    { code: 'SY', name: 'سوريا' },
    { code: 'IQ', name: 'العراق' },
    { code: 'PS', name: 'فلسطين' },
    { code: 'DZ', name: 'الجزائر' },
    { code: 'MA', name: 'المغرب' },
    { code: 'TN', name: 'تونس' },
    { code: 'LY', name: 'ليبيا' },
    { code: 'SO', name: 'الصومال' },
    { code: 'DJ', name: 'جيبوتي' },
    { code: 'KM', name: 'جزر القمر' },
    { code: 'MR', name: 'موريتانيا' },
    { code: 'US', name: 'الولايات المتحدة' },
    { code: 'GB', name: 'المملكة المتحدة' },
    { code: 'CA', name: 'كندا' },
    { code: 'AU', name: 'أستراليا' },
    { code: 'FR', name: 'فرنسا' },
    { code: 'DE', name: 'ألمانيا' },
    { code: 'IT', name: 'إيطاليا' },
    { code: 'ES', name: 'إسبانيا' },
    { code: 'TR', name: 'تركيا' },
    { code: 'IN', name: 'الهند' },
    { code: 'PK', name: 'باكستان' },
    { code: 'PH', name: 'الفلبين' },
    { code: 'BD', name: 'بنغلاديش' },
    { code: 'ID', name: 'إندونيسيا' },
    { code: 'LK', name: 'سريلانكا' },
    { code: 'NP', name: 'نيبال' },
    { code: 'MY', name: 'ماليزيا' },
    { code: 'CN', name: 'الصين' },
    { code: 'JP', name: 'اليابان' },
    { code: 'KR', name: 'كوريا الجنوبية' },
    { code: 'SG', name: 'سنغافورة' },
    { code: 'TH', name: 'تايلاند' },
    { code: 'VN', name: 'فيتنام' },
    { code: 'RU', name: 'روسيا' },
    { code: 'UA', name: 'أوكرانيا' },
    { code: 'ZA', name: 'جنوب أفريقيا' },
    { code: 'NG', name: 'نيجيريا' },
    { code: 'ET', name: 'إثيوبيا' },
    { code: 'KE', name: 'كينيا' },
    { code: 'GH', name: 'غانا' },
    { code: 'BR', name: 'البرازيل' },
    { code: 'MX', name: 'المكسيك' },
    { code: 'AR', name: 'الأرجنتين' },
    { code: 'CO', name: 'كولومبيا' },
    { code: 'VE', name: 'فنزويلا' },
    { code: 'AF', name: 'أفغانستان' },
    { code: 'IR', name: 'إيران' },
    { code: 'OTHER', name: 'أخرى / غير محدد' }
];
